import ExpoModulesCore
import CoreLocation

// RmpRouting is the Swift module generated by `uniffi-bindgen` from the Rust
// crate at mobile-core/rmp-routing.  Run `mobile-core/scripts/build-ios.sh`
// to produce the XCFramework and Generated/RmpRouting.swift before building.
//
// During development without the pre-built framework you can stub the types
// at the bottom of this file and swap them out once the build runs.
#if canImport(RmpRouting)
import RmpRouting
#endif

/// Expo native module — wraps the Rust `rmp-routing` solver for React Native.
///
/// Swift Concurrency (async/await) is used throughout so calls from JavaScript
/// never block the main thread.  The Rust functions are `Send + Sync` and
/// safe to call from any background executor.
public class RouteOptimizerModule: Module {

    public func definition() -> ModuleDefinition {
        Name("RouteOptimizer")

        // MARK: - Async route solver

        AsyncFunction("solveRoute") {
            (
                rawPoints: [[String: Any]],
                depotIndex: Int?,
                rawOptions: [String: Any]
            ) -> [String: Any] in

            let points  = try rawPoints.map(SolverPoint.from(dict:))
            let options = try SolverOptions.from(dict: rawOptions)
            let depot   = depotIndex.map { UInt32($0) }

            let result = try solveRoute(
                points:  points.map(\.asRust),
                depot:   depot,
                options: options.asRust
            )

            return result.asDictionary
        }

        // MARK: - Sync haversine helper (cheap enough for main thread)

        Function("haversineMeters") {
            (lat1: Double, lon1: Double, lat2: Double, lon2: Double) -> Double in
            haversineMeters(lat1: lat1, lon1: lon1, lat2: lat2, lon2: lon2)
        }
    }
}

// MARK: - Swift ↔ JS data models

private struct SolverPoint {
    let id: String
    let lat: Double
    let lon: Double
    let demand: Double?
    let serviceTime: Double?

    static func from(dict: [String: Any]) throws -> SolverPoint {
        guard
            let id  = dict["id"]  as? String,
            let lat = dict["lat"] as? Double,
            let lon = dict["lon"] as? Double
        else {
            throw RouteOptimizerError.invalidPoint
        }
        return SolverPoint(
            id:          id,
            lat:         lat,
            lon:         lon,
            demand:      dict["demand"]      as? Double,
            serviceTime: dict["serviceTime"] as? Double
        )
    }

    /// Map Swift coordinate (from CLLocationCoordinate2D, if needed) to Rust record.
    init(coordinate: CLLocationCoordinate2D, id: String, demand: Double? = nil, serviceTime: Double? = nil) {
        self.id          = id
        self.lat         = coordinate.latitude
        self.lon         = coordinate.longitude
        self.demand      = demand
        self.serviceTime = serviceTime
    }

    var asRust: RmpSolverPoint {
        RmpSolverPoint(
            id:          id,
            lat:         lat,
            lon:         lon,
            demand:      demand,
            serviceTime: serviceTime
        )
    }
}

private struct SolverOptions {
    let algorithm: RmpSolverAlgorithm
    let returnToDepot: Bool
    let maxIterations: UInt32?

    static func from(dict: [String: Any]) throws -> SolverOptions {
        let alg: RmpSolverAlgorithm
        switch (dict["algorithm"] as? String) ?? "2-opt" {
        case "nearest-neighbor": alg = .nearestNeighbor
        default:                 alg = .twoOpt
        }
        return SolverOptions(
            algorithm:     alg,
            returnToDepot: (dict["returnToDepot"] as? Bool) ?? false,
            maxIterations: (dict["maxIterations"] as? Int).map { UInt32($0) }
        )
    }

    var asRust: RmpSolverOptions {
        RmpSolverOptions(
            algorithm:     algorithm,
            returnToDepot: returnToDepot,
            maxIterations: maxIterations
        )
    }
}

// MARK: - Result → dictionary for JS bridge

extension RmpSolverResult {
    var asDictionary: [String: Any] {
        [
            "orderedIds":     orderedIds,
            "totalDistanceM": totalDistanceM,
            "totalDurationS": totalDurationS,
            "segments":       segments.map { seg in
                [
                    "fromId":    seg.fromId,
                    "toId":      seg.toId,
                    "distanceM": seg.distanceM,
                    "durationS": seg.durationS,
                ] as [String: Any]
            },
            "algorithm":    algorithm,
            "solveTimeMs":  solveTimeMs,
        ]
    }
}

// MARK: - Errors

enum RouteOptimizerError: Error, LocalizedError {
    case invalidPoint

    var errorDescription: String? {
        "SolverPoint must have 'id' (String), 'lat' (Double), and 'lon' (Double)."
    }
}

// MARK: - Stub types (used when RmpRouting.xcframework has not been built yet)
//
// Delete this section once `build-ios.sh` has been run and the XCFramework is
// linked into the Xcode project.

#if !canImport(RmpRouting)
enum RmpSolverAlgorithm { case nearestNeighbor, twoOpt }

struct RmpSolverPoint {
    var id: String; var lat: Double; var lon: Double
    var demand: Double?; var serviceTime: Double?
}

struct RmpSolverOptions {
    var algorithm: RmpSolverAlgorithm
    var returnToDepot: Bool
    var maxIterations: UInt32?
}

struct RmpRouteSegment {
    var fromId: String; var toId: String
    var distanceM: Double; var durationS: Double
}

struct RmpSolverResult {
    var orderedIds: [String]
    var totalDistanceM: Double; var totalDurationS: Double
    var segments: [RmpRouteSegment]
    var algorithm: String; var solveTimeMs: UInt64
}

enum RmpRoutingError: Error { case emptyInput, invalidDepot(UInt32) }

/// Fallback: pure-Swift nearest-neighbor so the module is usable without
/// the pre-built XCFramework during initial development.
func solveRoute(
    points: [RmpSolverPoint],
    depot: UInt32?,
    options: RmpSolverOptions
) throws -> RmpSolverResult {
    guard !points.isEmpty else { throw RmpRoutingError.emptyInput }
    let start = Date()
    var order = nearestNeighborSwift(points: points, depotIdx: Int(depot ?? 0))
    if options.returnToDepot { order.append(order[0]) }
    let (segs, dist, dur) = buildSegmentsSwift(order: order, points: points)
    return RmpSolverResult(
        orderedIds:     order.map { points[$0].id },
        totalDistanceM: dist,
        totalDurationS: dur,
        segments:       segs,
        algorithm:      "nearest-neighbor (Swift stub)",
        solveTimeMs:    UInt64(-start.timeIntervalSinceNow * 1000)
    )
}

func haversineMeters(lat1: Double, lon1: Double, lat2: Double, lon2: Double) -> Double {
    let R = 6_371_000.0
    let dLat = (lat2 - lat1) * .pi / 180
    let dLon = (lon2 - lon1) * .pi / 180
    let sinLat = sin(dLat / 2), sinLon = sin(dLon / 2)
    let a = sinLat*sinLat + cos(lat1 * .pi/180) * cos(lat2 * .pi/180) * sinLon*sinLon
    return R * 2 * atan2(a.squareRoot(), (1-a).squareRoot())
}

private func nearestNeighborSwift(points: [RmpSolverPoint], depotIdx: Int) -> [Int] {
    var visited = Array(repeating: false, count: points.len())
    var order = [depotIdx]; visited[depotIdx] = true
    while order.count < points.count {
        let last = order.last!
        let next = (0..<points.count)
            .filter { !visited[$0] }
            .min { haversineMeters(lat1: points[last].lat, lon1: points[last].lon, lat2: points[$0].lat, lon2: points[$0].lon) <
                   haversineMeters(lat1: points[last].lat, lon1: points[last].lon, lat2: points[$1].lat, lon2: points[$1].lon) }!
        visited[next] = true; order.append(next)
    }
    return order
}

private func buildSegmentsSwift(
    order: [Int], points: [RmpSolverPoint]
) -> ([RmpRouteSegment], Double, Double) {
    let speed = 30.0 * 1000.0 / 3600.0
    var segs = [RmpRouteSegment](); var dist = 0.0; var dur = 0.0
    for i in 0..<(order.count - 1) {
        let (f, t) = (order[i], order[i+1])
        let d = haversineMeters(lat1: points[f].lat, lon1: points[f].lon, lat2: points[t].lat, lon2: points[t].lon)
        let travel = d / speed
        let service = points[t].serviceTime ?? 120.0
        dist += d; dur += travel + service
        segs.append(RmpRouteSegment(fromId: points[f].id, toId: points[t].id, distanceM: d, durationS: travel + service))
    }
    return (segs, dist, dur)
}

private extension Array { func len() -> Int { count } }
#endif
