[package]
name = "rmp-optimizer"
version.workspace = true
edition.workspace = true

[dependencies]
rmp-shared = { path = "../shared" }

petgraph = { workspace = true }
nalgebra = { workspace = true }
geo = { workspace = true }
geojson = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
