package com.routemasterpro.routeoptimizer

import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.Promise
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

/**
 * Expo native module — Android side.
 *
 * The Rust rmp-routing library is loaded from a pre-built .so generated by
 * `mobile-core/scripts/build-android.sh`.  Until that script has been run,
 * a pure-Kotlin fallback (nearest-neighbor) is used automatically so the app
 * compiles without the native library present.
 */
class RouteOptimizerModule : Module() {

    companion object {
        private var nativeAvailable = false

        init {
            try {
                System.loadLibrary("rmp_routing")
                nativeAvailable = true
            } catch (_: UnsatisfiedLinkError) {
                // .so not present yet — fall back to Kotlin implementation
            }
        }

        // JNI declarations — matched by the UniFFI-generated JVM bindings.
        @JvmStatic external fun nativeSolveRoute(
            ids: Array<String>,
            lats: DoubleArray,
            lons: DoubleArray,
            demands: DoubleArray?,
            serviceTimes: DoubleArray?,
            depotIndex: Int,
            algorithm: Int,        // 0 = nearest-neighbor, 1 = 2-opt
            returnToDepot: Boolean,
            maxIterations: Int,
        ): DoubleArray // packed result — see unpackResult()

        @JvmStatic external fun nativeHaversineMeters(
            lat1: Double, lon1: Double, lat2: Double, lon2: Double
        ): Double
    }

    override fun definition() = ModuleDefinition {
        Name("RouteOptimizer")

        // MARK: - Async route solver

        AsyncFunction("solveRoute") { rawPoints: List<Map<String, Any?>>, depotIndex: Int?, rawOptions: Map<String, Any?>, promise: Promise ->
            CoroutineScope(Dispatchers.Default).launch {
                try {
                    val points  = rawPoints.map(::SolverPoint)
                    val options = SolverOptions(rawOptions)
                    val depot   = depotIndex ?: 0

                    val result = if (nativeAvailable) {
                        solveNative(points, depot, options)
                    } else {
                        solveKotlin(points, depot, options)
                    }

                    promise.resolve(result)
                } catch (e: Exception) {
                    promise.reject("ROUTING_ERROR", e.message ?: "Unknown error", e)
                }
            }
        }

        // MARK: - Sync haversine helper

        Function("haversineMeters") { lat1: Double, lon1: Double, lat2: Double, lon2: Double ->
            if (nativeAvailable) {
                nativeHaversineMeters(lat1, lon1, lat2, lon2)
            } else {
                haversineKotlin(lat1, lon1, lat2, lon2)
            }
        }
    }

    // ─── Native (Rust) path ───────────────────────────────────────────────────

    private fun solveNative(
        points: List<SolverPoint>,
        depotIndex: Int,
        options: SolverOptions,
    ): Map<String, Any> {
        val ids          = points.map { it.id }.toTypedArray()
        val lats         = points.map { it.lat }.toDoubleArray()
        val lons         = points.map { it.lon }.toDoubleArray()
        val demands      = points.map { it.demand ?: -1.0 }.toDoubleArray()
        val serviceTimes = points.map { it.serviceTime ?: -1.0 }.toDoubleArray()

        val raw = nativeSolveRoute(
            ids, lats, lons, demands, serviceTimes,
            depotIndex,
            options.algorithmCode,
            options.returnToDepot,
            options.maxIterations,
        )
        return unpackResult(raw, points)
    }

    // ─── Pure-Kotlin fallback (nearest-neighbor only) ─────────────────────────

    private fun solveKotlin(
        points: List<SolverPoint>,
        depotIndex: Int,
        options: SolverOptions,
    ): Map<String, Any> {
        if (points.isEmpty()) throw IllegalArgumentException("points list is empty")

        val start  = System.currentTimeMillis()
        val matrix = buildDistanceMatrix(points)
        val order  = nearestNeighbor(matrix, depotIndex).toMutableList()
        if (options.returnToDepot) order.add(depotIndex)

        val segments   = mutableListOf<Map<String, Any>>()
        var totalDist  = 0.0
        var totalDur   = 0.0
        val speedMs    = 30.0 * 1000.0 / 3600.0

        for (i in 0 until order.size - 1) {
            val from = order[i]; val to = order[i + 1]
            val dist    = matrix[from][to]
            val travel  = dist / speedMs
            val service = points[to].serviceTime ?: 120.0
            totalDist += dist; totalDur += travel + service
            segments.add(mapOf(
                "fromId"    to points[from].id,
                "toId"      to points[to].id,
                "distanceM" to dist,
                "durationS" to (travel + service),
            ))
        }

        return mapOf(
            "orderedIds"     to order.map { points[it].id },
            "totalDistanceM" to totalDist,
            "totalDurationS" to totalDur,
            "segments"       to segments,
            "algorithm"      to "nearest-neighbor (Kotlin fallback)",
            "solveTimeMs"    to (System.currentTimeMillis() - start),
        )
    }

    private fun buildDistanceMatrix(points: List<SolverPoint>): Array<DoubleArray> =
        Array(points.size) { i ->
            DoubleArray(points.size) { j ->
                if (i == j) 0.0
                else haversineKotlin(points[i].lat, points[i].lon, points[j].lat, points[j].lon)
            }
        }

    private fun nearestNeighbor(matrix: Array<DoubleArray>, depot: Int): List<Int> {
        val n       = matrix.size
        val visited = BooleanArray(n); visited[depot] = true
        val order   = mutableListOf(depot)
        while (order.size < n) {
            val last = order.last()
            val next = (0 until n).filter { !visited[it] }.minBy { matrix[last][it] }
            visited[next] = true; order.add(next)
        }
        return order
    }

    private fun unpackResult(raw: DoubleArray, points: List<SolverPoint>): Map<String, Any> {
        // Convention: packed array layout is defined by the UniFFI JVM binding glue.
        // Until that glue is generated this is a placeholder — real unpacking is
        // handled by the generated `rmp_routing.kt` file from uniffi-bindgen.
        return mapOf("error" to "unpackResult not yet wired to generated bindings")
    }

    private fun haversineKotlin(lat1: Double, lon1: Double, lat2: Double, lon2: Double): Double {
        val R     = 6_371_000.0
        val dLat  = Math.toRadians(lat2 - lat1)
        val dLon  = Math.toRadians(lon2 - lon1)
        val sinLat = Math.sin(dLat / 2); val sinLon = Math.sin(dLon / 2)
        val a = sinLat * sinLat + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2)) * sinLon * sinLon
        return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
    }
}

// ─── Data classes ─────────────────────────────────────────────────────────────

private data class SolverPoint(
    val id: String,
    val lat: Double,
    val lon: Double,
    val demand: Double?,
    val serviceTime: Double?,
) {
    constructor(dict: Map<String, Any?>) : this(
        id          = dict["id"]          as? String ?: error("SolverPoint.id is required"),
        lat         = (dict["lat"]         as? Number)?.toDouble() ?: error("SolverPoint.lat is required"),
        lon         = (dict["lon"]         as? Number)?.toDouble() ?: error("SolverPoint.lon is required"),
        demand      = (dict["demand"]      as? Number)?.toDouble(),
        serviceTime = (dict["serviceTime"] as? Number)?.toDouble(),
    )
}

private data class SolverOptions(
    val algorithmCode: Int,    // 0 = nearest-neighbor, 1 = 2-opt
    val returnToDepot: Boolean,
    val maxIterations: Int,
) {
    constructor(dict: Map<String, Any?>) : this(
        algorithmCode = when (dict["algorithm"] as? String) {
            "nearest-neighbor" -> 0
            else               -> 1
        },
        returnToDepot = (dict["returnToDepot"] as? Boolean) ?: false,
        maxIterations = (dict["maxIterations"] as? Number)?.toInt() ?: 100,
    )
}
