[package]
name = "rmp-db"
version.workspace = true
edition.workspace = true

[dependencies]
rmp-shared = { path = "../shared" }

sqlx = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
